name: CI Pipeline - SGE

# Ejecutar cuando haya push a la rama main
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Descargar el código
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Instalar PHP 8.2 y MySQL
      - name: Setup PHP & MySQL
        run: |
          sudo apt-get update
          sudo apt-get install -y php8.2 php8.2-mysql mysql-server

      # 3️⃣ Configurar MySQL root y crear base de datos
      - name: Configure MySQL
        run: |
          sudo service mysql start
          sudo mysql <<EOF
          ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY '1234';
          FLUSH PRIVILEGES;
          CREATE DATABASE IF NOT EXISTS sistema_gestion_educativa;
          USE sistema_gestion_educativa;
          SOURCE ./sql/procedimientos.sql;
          EOF

      # 4️⃣ Validaciones básicas de archivos
      - name: Check critical files
        run: |
          if [ ! -f "index.php" ]; then
            echo "Error: index.php no encontrado"
            exit 1
          fi
          if [ ! -f "conexion.php" ]; then
            echo "Error: conexion.php no encontrado"
            exit 1
          fi

      # 5️⃣ Probar conexión PHP-MySQL (opcional)
      - name: Test PHP MySQL Connection
        run: |
          php -r "
          \$conn = new mysqli('localhost', 'root', '1234', 'sistema_gestion_educativa');
          if (\$conn->connect_error) { exit(1); } else { echo 'Conexión OK\n'; }
          \$conn->close();
          "
