name: CI Pipeline - SGE

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: 1234
          MYSQL_DATABASE: sistema_gestion_educativa
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      # 1️⃣ Descargar código
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Instalar PHP y extensiones
      - name: Set up PHP 8.2 and extensions
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mysqli, mbstring, xml

      # 3️⃣ Esperar a que MySQL esté listo
      - name: Wait for MySQL
        run: |
          until mysqladmin ping -h 127.0.0.1 -uroot -p1234 --silent; do
            echo "Waiting for MySQL..."
            sleep 3
          done

      # 4️⃣ Crear usuario CI y otorgar permisos
      - name: Configure MySQL user for CI
        run: |
          mysql -h 127.0.0.1 -uroot -p1234 -e "CREATE USER IF NOT EXISTS 'ciuser'@'%' IDENTIFIED BY 'ci_pass';"
          mysql -h 127.0.0.1 -uroot -p1234 -e "GRANT ALL PRIVILEGES ON *.* TO 'ciuser'@'%'; FLUSH PRIVILEGES;"

      # 5️⃣ Ejecutar scripts SQL
      - name: Run SQL scripts
        run: |
          mysql -h 127.0.0.1 -uciuser -pci_pass sistema_gestion_educativa < ./sql/procedimientos.sql

      # 6️⃣ Validaciones básicas
      - name: Check critical files
        run: |
          if [ ! -f "index.php" ]; then echo "index.php no encontrado" && exit 1; fi
          if [ ! -f "conexion.php" ]; then echo "conexion.php no encontrado" && exit 1; fi

      # 7️⃣ Test simple de PHP
      - name: Test PHP connection
        run: |
          php -r "if (extension_loaded('mysqli')) { echo 'MySQLi OK'; } else { echo 'MySQLi missing'; exit(1); }"
