name: CI Pipeline - SGE

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: 1234
          MYSQL_DATABASE: sistema_gestion_educativa
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      # 1️⃣ Descargar código
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Instalar PHP 8.2 y extensiones necesarias
      - name: Set up PHP 8.2 and extensions
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mysqli, mbstring, xml, pdo_mysql, xdebug
          coverage: xdebug

      # 3️⃣ Instalar Composer
      - name: Install Composer
        run: |
          curl -sS https://getcomposer.org/installer | php
          sudo mv composer.phar /usr/local/bin/composer

      # 4️⃣ Esperar a que MySQL esté listo
      - name: Wait for MySQL
        run: |
          echo "Esperando a que MySQL esté listo..."
          until mysqladmin ping -h 127.0.0.1 -uroot -p1234 --silent; do
            echo "Waiting for MySQL..."
            sleep 3
          done
          echo "MySQL is ready!"

      # 5️⃣ Crear usuario CI y otorgar permisos
      - name: Configure MySQL user for CI
        run: |
          mysql -h 127.0.0.1 -uroot -p1234 -e "CREATE USER IF NOT EXISTS 'ciuser'@'%' IDENTIFIED BY 'ci_pass';"
          mysql -h 127.0.0.1 -uroot -p1234 -e "GRANT ALL PRIVILEGES ON *.* TO 'ciuser'@'%'; FLUSH PRIVILEGES;"

      # 6️⃣ Ejecutar scripts SQL
      - name: Run SQL scripts
        run: |
          if [ ! -f "./sql/estructura.sql" ]; then
            echo "Error: ./sql/estructura.sql no encontrado"
            exit 1
          fi
          if [ ! -f "./sql/procedimientos.sql" ]; then
            echo "Error: ./sql/procedimientos.sql no encontrado"
            exit 1
          fi

          echo "Ejecutando estructura.sql..."
          mysql -h 127.0.0.1 -uciuser -pci_pass sistema_gestion_educativa < ./sql/estructura.sql

          echo "Ejecutando procedimientos.sql..."
          mysql -h 127.0.0.1 -uciuser -pci_pass sistema_gestion_educativa < ./sql/procedimientos.sql

          echo "SQL ejecutado correctamente"

      # 7️⃣ Configurar variables de entorno para tests
      - name: Set environment variables for DB
        run: |
          echo "DB_HOST=127.0.0.1" >> $GITHUB_ENV
          echo "DB_NAME=sistema_gestion_educativa" >> $GITHUB_ENV
          echo "DB_USER=ciuser" >> $GITHUB_ENV
          echo "DB_PASS=ci_pass" >> $GITHUB_ENV

      # 8️⃣ Validaciones básicas de archivos
      - name: Check critical files
        run: |
          for file in index.php conexion.php; do
            if [ ! -f "$file" ]; then echo "$file no encontrado" && exit 1; fi
          done

      # 9️⃣ Test rápido de conexión PHP a MySQL
      - name: Test PHP MySQL connection
        run: |
          php -r "
          \$mysqli = new mysqli(getenv('DB_HOST'), getenv('DB_USER'), getenv('DB_PASS'), getenv('DB_NAME'));
          if (\$mysqli->connect_error) { echo 'MySQL connection failed: ' . \$mysqli->connect_error; exit(1); }
          echo 'MySQL connection OK';"

      # 🔟 Instalar dependencias de Composer
      - name: Install dependencies
        run: composer install --no-interaction --prefer-dist

      # 1️⃣1️⃣ Ejecutar PHPUnit con todos los tests
      - name: Run PHPUnit tests
        run: |
          chmod +x ./vendor/bin/phpunit
          if [ -f "phpunit.xml" ]; then
            echo "Usando phpunit.xml"
            ./vendor/bin/phpunit --configuration phpunit.xml --testdox --colors=always --coverage-text || true
          else
            echo "No phpunit.xml found, running individual tests"
            ./vendor/bin/phpunit tests/ConexionTest.php || true
            ./vendor/bin/phpunit tests/UsuarioModeloTest.php || true
            ./vendor/bin/phpunit tests/UsuarioControllerTest.php || true
          fi
        shell: /usr/bin/bash -e {0}
        env:
          COMPOSER_PROCESS_TIMEOUT: 0
          COMPOSER_NO_INTERACTION: 1
          COMPOSER_NO_AUDIT: 1
          DB_HOST: 127.0.0.1
          DB_NAME: sistema_gestion_educativa
          DB_USER: ciuser
          DB_PASS: ci_pass