name: CI Pipeline - SGE

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Descargar código
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Instalar PHP y extensiones
      - name: Set up PHP 8.2 and extensions
        run: |
          sudo apt-get update
          sudo apt-get install -y software-properties-common
          sudo add-apt-repository ppa:ondrej/php -y
          sudo apt-get update
          sudo apt-get install -y php8.2 php8.2-cli php8.2-mysql php8.2-mbstring php8.2-xml unzip

      # 3️⃣ Instalar MySQL
      - name: Install MySQL
        run: |
          sudo apt-get install -y mysql-server
          sudo service mysql start

      # 4️⃣ Configurar usuario temporal para CI
      - name: Configure MySQL user for CI
        run: |
          sudo mysql -e "CREATE USER IF NOT EXISTS 'ciuser'@'localhost' IDENTIFIED BY 'ci_pass';"
          sudo mysql -e "GRANT ALL PRIVILEGES ON *.* TO 'ciuser'@'localhost'; FLUSH PRIVILEGES;"
          sudo mysql -u ciuser -pci_pass -e "CREATE DATABASE IF NOT EXISTS sistema_gestion_educativa;"

      # 5️⃣ Ejecutar scripts SQL
      - name: Run SQL scripts
        run: |
          sudo mysql -u ciuser -pci_pass sistema_gestion_educativa < ./sql/procedimientos.sql

      # 6️⃣ Validaciones básicas
      - name: Check critical files
        run: |
          if [ ! -f "index.php" ]; then echo "index.php no encontrado" && exit 1; fi
          if [ ! -f "conexion.php" ]; then echo "conexion.php no encontrado" && exit 1; fi

      # 7️⃣ Test simple de PHP
      - name: Test PHP connection
        run: |
          php -r "if (extension_loaded('mysqli')) { echo 'MySQLi OK'; } else { echo 'MySQLi missing'; exit(1); }"
