name: CI Pipeline - SGE

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Descargar código
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Instalar PHP y MySQL
      - name: Install PHP & MySQL
        run: |
          sudo apt-get update
          sudo apt-get install -y php8.2 php8.2-mysql mysql-server
          sudo service mysql start

      # 3️⃣ Configurar MySQL y ejecutar script SQL
      - name: Configure MySQL & Run SQL
        run: |
          sudo mysql <<EOF
          ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY '1234';
          FLUSH PRIVILEGES;
          CREATE DATABASE IF NOT EXISTS sistema_gestion_educativa;
          USE sistema_gestion_educativa;
          SOURCE ./sql/procedimientos.sql;
          EOF

      # 4️⃣ Validar archivos críticos
      - name: Check critical files
        run: |
          if [ ! -f "index.php" ] || [ ! -f "conexion.php" ]; then
            echo "Faltan archivos críticos"
            exit 1
          fi

      # 5️⃣ Opcional: Prueba rápida de conexión PHP a MySQL
      - name: Test PHP-MySQL connection
        run: |
          php -r "
          \$conn = new mysqli('localhost', 'root', '1234', 'sistema_gestion_educativa');
          if (\$conn->connect_error) { exit(1); }
          exit(0);
          "
