name: CI Pipeline - SGE

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Descargar código
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Instalar PHP y MySQL
      - name: Set up PHP and MySQL
        run: |
          sudo apt-get update
          sudo apt-get install -y php8.2 php8.2-mysql mysql-server
          sudo service mysql start

      # 3️⃣ Configurar la base de datos
      - name: Configure MySQL
        run: |
          sudo mysql -e "ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY '1234'; FLUSH PRIVILEGES;"
          sudo mysql -u root -p1234 -e "CREATE DATABASE IF NOT EXISTS sistema_gestion_educativa;"
          sudo mysql -u root -p1234 sistema_gestion_educativa < ./sql/procedimientos.sql

      # 4️⃣ Validaciones básicas de archivos
      - name: Check critical files
        run: |
          if [ ! -f "index.php" ]; then exit 1; fi
          if [ ! -f "conexion.php" ]; then exit 1; fi
