name: CI Pipeline - SGE

on:
  push:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'

    - name: Check critical files
      run: |
        if [ ! -f "index.php" ]; then exit 1; fi
        if [ ! -f "conexion.php" ]; then exit 1; fi

    - name: Install MySQL and run scripts
      run: |
        sudo apt-get update
        sudo apt-get install -y mysql-server
        sudo service mysql start
        mysql -e "ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY '1234'; FLUSH PRIVILEGES;"
        mysql -e "CREATE DATABASE IF NOT EXISTS sistema_gestion_educativa;"
        mysql -uroot -p1234 sistema_gestion_educativa < ./sql/procedimientos.sql

    - name: Test project endpoint
      run: |
        curl -I http://localhost/SGE/index.php || echo "No se pudo acceder a index.php"
